version: "3.7"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - METRICS_DB_URI=postgresql://postgres:postgres@db:5432/metrics
      - TESTO_DB_URI=postgresql://postgres:postgres@db:5432/testo
    ports:
      - 8080:8080
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - my-postgres:/var/lib/postgresql/data
  grafana:
    image: grafana/grafana:5.4.5
    ports:
      - 8081:3000
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - db

volumes:
  my-postgres:
